# Day 17 - Qdrant Vector Database & Semantic Search

This notebook demonstrates:
- Generating 384-dimensional embeddings
- Creating a Qdrant collection
- Uploading vectors
- Semantic search
- Metadata filtering

**No LLM is used today.**

In [15]:
# !pip install sentence-transformers qdrant-client pandas

from sentence_transformers import SentenceTransformer
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance, VectorParams, PointStruct, Filter, FieldCondition, MatchValue
import pandas as pd
import os
from dotenv import load_dotenv

# 1. Load the environment variables from your .env file
load_dotenv()

# Verify the key is loaded (don't print the actual key in output!)
if not os.getenv("HF_TOKEN"):
    raise ValueError("HF_TOKEN not found. Please check your .env file.")

model=SentenceTransformer("all-MiniLM-L6-v2")
client=QdrantClient(host="localhost",port=6333)
print("Connected")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Connected

#### Chunks
Assuming, We already have done the chunking

Q: How many vacation days do employees receive?

In [2]:
documents=[
{"department":"HR","text":"Employees receive 18 days of annual leave every year."},
{"department":"HR","text":"Medical leave allows up to 10 days annually."},
{"department":"Travel","text":"International travel requires VP approval."},
{"department":"Travel","text":"Hotel expenses are reimbursed up to company limits."},
{"department":"IT","text":"Company laptops are replaced every four years."},
{"department":"IT","text":"VPN access is mandatory for remote work."},
{"department":"Finance","text":"Expense claims should be submitted within 30 days."},
{"department":"Finance","text":"Salary is credited on the last working day of every month."},
{"department":"Engineering","text":"Python is the preferred language for AI projects."},
{"department":"Engineering","text":"Docker containers simplify deployment."}
]
pd.DataFrame(documents)

    department                                               text
0           HR  Employees receive 18 days of annual leave ever...
1           HR       Medical leave allows up to 10 days annually.
2       Travel         International travel requires VP approval.
3       Travel  Hotel expenses are reimbursed up to company li...
4           IT     Company laptops are replaced every four years.
5           IT           VPN access is mandatory for remote work.
6      Finance  Expense claims should be submitted within 30 d...
7      Finance  Salary is credited on the last working day of ...
8  Engineering  Python is the preferred language for AI projects.
9  Engineering             Docker containers simplify deployment.

In [3]:
texts=[d["text"] for d in documents]
embeddings=model.encode(texts)
print(embeddings.shape)

(10, 384)

In [16]:
embeddings[0]

array([ 6.49055317e-02,  6.08355887e-02,  6.96704015e-02,  1.78844016e-02,
        4.16478282e-03,  6.06948249e-02, -4.95865606e-02, -8.68155062e-02,
       -2.24852990e-02, -6.53456375e-02,  4.92458269e-02,  3.05002593e-02,
       -7.14240149e-02, -4.38691676e-02, -1.73113178e-02,  2.38916967e-02,
       -5.92406690e-02, -2.23403201e-02,  7.71416677e-03, -9.66793895e-02,
       -1.97028480e-02, -6.46564141e-02, -4.62503470e-02, -7.10236328e-03,
        9.37251281e-03,  2.90031196e-03, -1.61035676e-02, -4.17879224e-02,
       -2.76322719e-02,  6.38967529e-02,  4.20686044e-02,  6.05626851e-02,
        2.73725539e-02, -3.21392864e-02,  4.91284905e-03,  1.69611268e-03,
       -4.38027419e-02, -3.92892817e-03,  1.74630322e-02,  1.94096453e-02,
       -3.93981747e-02,  3.58626060e-02,  8.89555290e-02, -2.66630892e-02,
       -1.14394072e-02, -2.06949245e-02, -8.14028531e-02,  4.05333303e-02,
        6.19838126e-02,  1.35150969e-01,  9.75810736e-02,  4.73400652e-02,
        5.35129122e-02,  1.14719898e-01,  1.48191433e-02, -3.61302346e-02,
        1.92442164e-02, -1.08390205e-01,  2.08711196e-02, -6.40555192e-03,
        2.44707849e-06,  5.61230443e-03, -2.55527366e-02, -4.83690351e-02,
       -4.78712805e-02, -8.05123597e-02,  5.63319214e-02, -6.59399703e-02,
       -2.74518132e-02, -4.66285758e-02, -1.57846123e-01, -1.42227253e-03,
       -7.08649904e-02, -1.06167020e-02,  1.16477748e-02,  5.41089326e-02,
        2.04354338e-03,  6.20547906e-02,  8.95200521e-02, -5.32940403e-02,
       -1.62188546e-03,  8.96489471e-02,  6.96555004e-02,  7.19127506e-02,
       -1.64779965e-02, -3.38060409e-02,  3.34308036e-02,  6.03103451e-02,
        6.59822375e-02,  6.01819642e-02,  2.26615760e-02,  1.51914833e-02,
        8.45652353e-03, -2.99150534e-02, -9.03219506e-02, -1.24828152e-01,
       -3.58292609e-02,  6.38271272e-02,  1.18637104e-02,  2.01191809e-02,
        2.99405772e-02,  4.04467690e-04,  4.28357441e-03, -3.77604887e-02,
       -1.07878949e-02,  1.51531482e-02,  2.73213219e-02, -3.62808891e-02,
       -6.06546178e-02, -1.63259748e-02, -2.13800371e-02,  9.50454772e-02,
       -5.73703367e-03,  1.67350401e-03,  4.25920710e-02,  5.49190938e-02,
       -9.84979793e-02,  4.94359061e-02,  6.40005469e-02,  6.66267201e-02,
        1.20503567e-01,  9.73051563e-02, -1.60119273e-02,  1.48600060e-02,
       -1.08892195e-01, -1.77755877e-02,  1.79171246e-02, -1.60491236e-33,
        4.16990779e-02,  6.40128041e-03, -3.33423098e-03,  3.34923752e-02,
        9.62770134e-02, -9.23824310e-02, -5.96191362e-02, -2.05552615e-02,
        5.56543097e-02, -3.01368982e-02, -4.92690839e-02, -1.59109440e-02,
        4.59028035e-02, -8.51111263e-02,  1.23734564e-01,  2.62755100e-02,
        6.14927188e-02,  6.93969131e-02,  5.25582097e-02, -2.54950318e-02,
        4.98667881e-02, -7.02964440e-02,  2.82794069e-02,  1.16565125e-02,
        2.36779638e-02, -3.18881832e-02, -6.94099143e-02, -8.65032617e-03,
       -2.58380231e-02, -6.56128442e-03,  1.19515769e-01,  1.36977993e-02,
        1.00861229e-02, -3.83727960e-02, -9.03505459e-03, -4.12544459e-02,
        3.52463648e-02,  3.83020602e-02,  4.49231304e-02, -1.06339172e-01,
       -6.59257220e-03, -2.68880948e-02,  2.91431807e-02,  3.91416699e-02,
        5.22034392e-02, -5.13854735e-02,  1.37761338e-02, -6.35689050e-02,
        3.23218741e-02,  1.04798056e-01, -2.15446893e-02, -2.34004091e-02,
        6.14922307e-02, -6.63237423e-02,  2.69177482e-02,  3.07262372e-02,
       -3.42547172e-03,  5.00920461e-03,  5.87395430e-02, -4.13026772e-02,
        8.33673961e-03,  6.19985387e-02,  3.64489928e-02,  2.85005327e-02,
       -2.50727125e-02,  1.99591834e-02,  3.06702349e-02, -2.42486801e-02,
        3.66526768e-02,  4.33029942e-02,  1.63566694e-02,  2.51818709e-02,
       -1.34458523e-02, -9.55483839e-02, -4.80718911e-02, -1.52699091e-02,
        4.73336242e-02, -7.40156546e-02,  2.24931240e-02,  6.44722655e-02,
        4.74825241e-02,  5.67756854e-02, -4.82103415e-03, -9.54537392e-02,
        1.07951358e-01,  3.22955777e-03,  5.56504838e-02,  6.06323145e-02,
        3.38766426e-02, -9.19529423e-03,  9.56452340e-02, -1.32913813e-01,
       -2.54639722e-02, -6.22255122e-03,  5.89483604e-02,  1.63641590e-34,
        4.39434685e-02,  4.32536453e-02,  2.45393328e-02, -9.49197635e-02,
        1.38523886e-02, -2.70156711e-02,  6.82926131e-03,  1.19469821e-01,
       -1.42072067e-02,  6.70710057e-02,  7.32772425e-03, -3.15884911e-02,
       -1.00461408e-01,  5.20297661e-02, -1.83461013e-03,  1.23368856e-02,
        7.19059184e-02, -7.62311518e-02, -5.82454018e-02, -2.93607488e-02,
       -4.46054004e-02,  8.94792192e-03, -1.69411562e-02,  3.17570455e-02,
        7.79108563e-03,  4.44213413e-02, -2.85381898e-02, -1.74848940e-02,
       -5.68678007e-02, -7.64202280e-03, -1.02823101e-01, -3.66511717e-02,
        3.57097201e-03,  6.28050789e-02,  6.22352250e-02, -1.28122583e-01,
       -7.43215904e-02,  3.13011110e-02,  3.18931229e-02,  1.09719828e-01,
       -1.00415675e-02, -6.69346526e-02,  9.18087438e-02,  5.27135395e-02,
       -3.02712731e-02,  8.25388283e-02, -1.05909750e-01, -3.79988067e-02,
       -6.30531982e-02, -1.16333682e-02,  1.07543385e-02, -3.73867676e-02,
       -5.90740852e-02, -1.94629487e-02, -1.75763238e-02,  4.88928473e-03,
       -9.92920157e-03, -2.74887383e-02, -6.27713352e-02, -8.38321354e-03,
        5.69705628e-02, -7.34711885e-02, -1.05891749e-02,  2.43382417e-02,
       -5.33363037e-02, -4.30245772e-02, -5.81986550e-03, -1.12352241e-02,
        2.21034754e-02, -2.71045398e-02,  6.86049601e-03,  1.29391858e-02,
       -1.81153677e-02, -7.81302005e-02, -2.98590194e-02,  1.78214256e-02,
        6.40917867e-02, -4.59555984e-02, -2.39334758e-02,  1.43244024e-02,
       -7.17755631e-02, -3.49902752e-04,  1.52213443e-02,  3.94102968e-02,
        1.18899356e-04, -8.86683539e-02,  1.99917872e-02, -5.25424331e-02,
       -1.81856975e-02,  9.39763337e-02,  9.54321176e-02, -1.18479416e-01,
        4.16850345e-03,  7.76088517e-03,  3.50032002e-02, -1.73290520e-08,
        4.54706028e-02,  5.14829494e-02,  2.63076164e-02, -3.98099162e-02,
       -8.39830842e-03, -1.07757092e-01,  3.46552953e-02, -4.96586934e-02,
        1.51676536e-02,  3.69468667e-02,  7.21465796e-02, -1.18073132e-02,
       -1.86030548e-02, -1.93920042e-02,  9.87085234e-03,  2.92922650e-02,
       -8.90461076e-03,  6.28421381e-02, -3.31251174e-02, -2.60600802e-02,
       -1.70088932e-02,  3.20079029e-02, -2.03465112e-02, -1.39852064e-02,
       -2.30978504e-02,  3.45066227e-02, -3.09178978e-03,  3.27596813e-02,
        3.33000906e-02,  5.81920287e-03,  2.83092819e-02, -5.55938482e-03,
        7.85900559e-03, -2.90566050e-02, -3.87605838e-02, -3.17443945e-02,
       -1.91255528e-02, -1.16427653e-01,  4.31255903e-03, -2.89023966e-02,
        1.13741308e-02,  3.55332047e-02,  9.06056724e-03, -1.75554361e-02,
       -1.84266698e-02, -2.85113286e-02, -7.37058744e-02, -1.02596972e-02,
       -3.13771628e-02,  1.85881462e-03,  6.09177686e-02, -6.05546124e-02,
        3.12985480e-02,  3.12838890e-02, -5.20136487e-03, -1.10106878e-02,
       -5.89082297e-03, -8.86367634e-02, -5.03213927e-02, -5.40173426e-02,
       -5.68422638e-02,  2.01845597e-02,  4.39573973e-02,  9.84304701e-04],
      dtype=float32)

In [17]:
COLLECTION="employee_docs"
try:
    client.delete_collection(COLLECTION)
except:
    pass
client.create_collection(
    collection_name=COLLECTION,
    vectors_config=VectorParams(size=384,distance=Distance.COSINE)
)
points=[]
for i,(doc,vec) in enumerate(zip(documents,embeddings)):
    points.append(PointStruct(id=i,vector=vec.tolist(),payload=doc))
client.upsert(collection_name=COLLECTION,points=points)
print("Uploaded",len(points),"documents. Each doc is a point (position-vector)")

Uploaded 10 documents. Each doc is a point (position-vector)

#### Retrieve first three!

In [18]:
first_three = client.retrieve(collection_name=COLLECTION, ids=[0, 1, 2])
pd.DataFrame(first_three)

,0,1,2,3,4
0,"(id, 0)","(payload, {'department': 'HR', 'text': 'Employ...","(vector, None)","(shard_key, None)","(order_value, None)"
1,"(id, 1)","(payload, {'department': 'HR', 'text': 'Medica...","(vector, None)","(shard_key, None)","(order_value, None)"
2,"(id, 2)","(payload, {'department': 'Travel', 'text': 'In...","(vector, None)","(shard_key, None)","(order_value, None)"

In [19]:
def semantic_search(query,top_k=3):
    q=model.encode(query).tolist()
    results=client.query_points(collection_name=COLLECTION,
                                query=q,limit=top_k).points
    print("\nQuery:",query)
    print("-"*60)
    for r in results:
        print(f"Score: {r.score:.4f}")
        print("Department:",r.payload["department"])
        print(r.payload["text"])
        print()

semantic_search("How many vacation days do employees receive?")
# semantic_search("Who approves international travel?")
# semantic_search("How often are laptops replaced?")

Query: How many vacation days do employees receive?
------------------------------------------------------------
Score: 0.6881
Department: HR
Employees receive 18 days of annual leave every year.

Score: 0.4632
Department: HR
Medical leave allows up to 10 days annually.

Score: 0.4443
Department: Finance
Salary is credited on the last working day of every month.

In [14]:
query="travel approval"
q=model.encode(query).tolist()
results=client.query_points(
    collection_name=COLLECTION,
    query=q,
    query_filter=Filter(
        must=[
            FieldCondition(
                key="department",
                match=MatchValue(value="Travel")
            )
        ]
    ),
    limit=3
).points

for r in results:
    print(r.payload)
    print("Score:",round(r.score,4))
    print()

{'department': 'Travel', 'text': 'International travel requires VP approval.'}
Score: 0.6368

{'department': 'Travel', 'text': 'Hotel expenses are reimbursed up to company limits.'}
Score: 0.2565

## Summary

Today we learned:

- A vector database stores embeddings.
- Each vector is associated with metadata (payload).
- Semantic search retrieves the nearest vectors.
- Metadata filtering narrows the search.

Tomorrow we will connect the retriever to an LLM to build a complete RAG pipeline.